### PR TITLE
Add Python linter to CI

### PR DESCRIPTION
**Pull request by mwperina**
- Run flake8 when Python source codes are changed
- Fix issues detected by flake8

### CODE REVIEW

**Review by engelmi — COMMENTED** [review]
I like having the python linting in the workflow. However, I'd rather move (and duplicate) the `setup.cfg` to the `doc/api-examples` and `tests` directory as these can be considered "different projects" - otherwise hirte a C project. In the `tests` we currently use `autopep8` for code formatting, which can be replaced by `flake8`.

**Comment by mwperina** [comment]
> I like having the python linting in the workflow. However, I'd rather move (and duplicate) the `setup.cfg` to the `doc/api-examples` and `tests` directory as these can be considered "different projects" - otherwise hirte a C project.

Having `setup.cfg` in the top level directory allows us to run `flake8` once for the whole project no matter where the python files are located. If the file is moved to `tests` and `doc/api-examples`, then we would need to run flake8 for each directory separately.

> In the `tests` we currently use `autopep8` for code formatting, which can be replaced by `flake8`.

flake8 contains pycodestyle plugin, which checks the code according to the PEP8

**Comment by engelmi** [comment]
> flake8 contains pycodestyle plugin, which checks the code according to the PEP8

Yes, but does flake8 also use the `.pep8` file and the configuration in there?  If so, which specified `line_length` is being used? 
Edit: I think we can remive the pep file in the test directory and use the setup.cfg as single source. 

> Having `setup.cfg` in the top level directory allows us to run `flake8` once for the whole project no matter where the python files are located. If the file is moved to `tests` and `doc/api-examples`, then we would need to run flake8 for each directory separately.

In the CI it is run for each found .py file individually: 
https://github.com/containers/hirte/pull/273/files#diff-14721317565b7c66355f276ec27762054b12f390afd6c35fba85cfaf77d311c7R40-R42
Instead of searching everywhere, we'd be more specific and search only those two directories.

**Comment by mwperina** [comment]
> > flake8 contains pycodestyle plugin, which checks the code according to the PEP8
> 
> Yes, but does flake8 also use the `.pep8` file and the configuration in there? If so, which specified `line_length` is being used? Edit: I think we can remive the pep file in the test directory and use the setup.cfg as single source.

Unless I'm missing something `.pep8` in `tests` subdirectory would be used only if `flake8` is executed from this directory:

https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations

> 
> > Having `setup.cfg` in the top level directory allows us to run `flake8` once for the whole project no matter where the python files are located. If the file is moved to `tests` and `doc/api-examples`, then we would need to run flake8 for each directory separately.
> 
> In the CI it is run for each found .py file individually: https://github.com/containers/hirte/pull/273/files#diff-14721317565b7c66355f276ec27762054b12f390afd6c35fba85cfaf77d311c7R40-R42 Instead of searching everywhere, we'd be more specific and search only those two directories.

Well, then we would need to know that limitation in future when (if) we add python files into a different directory

**Comment by engelmi** [comment]
> Well, then we would need to know that limitation in future when (if) we add python files into a different directory

I'd prefer it to be explicit (similar to mesons approach), but I think it doesn't matter in our case.

**Review by engelmi — APPROVED** [review]
LGTM

**Pull request merged**
