### PR TITLE
Add lsof for integration-test-base

### PR DESCRIPTION
**Pull request by ArtiomDivak**
lsof needed to check if port connected inside
controller/agent container.

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
LGTM

**Review by engelmi — COMMENTED** [review]
Why exactly is this necessary? Shouldn't it be sufficient/better to use the current tooling like bluechictl to check if the agent is connected?

Note: This also requires rebuilding the image and pushing to quay.io.

**Review by engelmi — DISMISSED** [review]
Follow up of https://github.com/eclipse-bluechi/bluechi/pull/696#pullrequestreview-1812633254:
This is how it was done previously:
https://github.com/eclipse-bluechi/bluechi/blob/main/tests/tests/tier0/monitor-node-reconnect/python/is_node_connected.py

**Comment by mwperina** [comment]
> Follow up of [#696 (review)](https://github.com/eclipse-bluechi/bluechi/pull/696#pullrequestreview-1812633254): This is how it was done previously: https://github.com/eclipse-bluechi/bluechi/blob/main/tests/tests/tier0/monitor-node-reconnect/python/is_node_connected.py

We should check that a different port passed though command line option has been accepted by controller and the controller started to listen on a different port

**Comment by engelmi** [comment]
> We should check that a different port passed though command line option has been accepted by controller and the controller started to listen on a different port

And changing the port for both, controller and agent, observing the disconnect and (after changing the agent) the reconnect of the agent is "too high level", I guess, since we are not really verify the new port. 
Makes sense, I think. Was just trying to understand this change.

**Comment by mwperina** [comment]
> > We should check that a different port passed though command line option has been accepted by controller and the controller started to listen on a different port
> 
> And changing the port for both, controller and agent, observing the disconnect and (after changing the agent) the reconnect of the agent is "too high level", I guess, since we are not really verify the new port. Makes sense, I think. Was just trying to understand this change.

My test thoughts: https://github.com/eclipse-bluechi/bluechi/pull/680#issuecomment-1884398573
So for checking controller actually accepted new port configuration we need a tool like lsof

**Review by engelmi — APPROVED** [review]
LGTM

**Pull request merged**
