### PR TITLE
added initial dbus policy file templates and meson installation

### LINKED ISSUE #164: Research D-Bus permissions
This issue is to research D-Bus permissions, and how to prevent unauthorized users from sending
messages on a bus.  The long term goal is to run Hirte on the system bus, and the system bus by
default is limited for any user except root.  There is an XML file for opening up access rights, and
that's how you can control who can do what.

### PR DESCRIPTION
**Pull request by engelmi**
This PR adds initial policy configuration files to grant `hirte` and `hirte-agent` to own the specified names on the system bus.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by mwperina — APPROVED** [review]
+1

**Review by mwperina — COMMENTED** [review]
Could you please also enable usage of system dbus when building the project from RPM spec file?
Something like:
```
%meson_build -Dapi_bus=system
```

**Comment by engelmi** [comment]
> Could you please also enable usage of system dbus when building the project from RPM spec file? Something like:
> 
> ```
> %meson_build -Dapi_bus=system
> ```
Sure, added it. If the CI runs successful, I'll merge.

**Pull request merged**
