### PR TITLE
Improve readability of markdown files

### PR DESCRIPTION
**Pull request by raballew**
The following changes have been applied:

- Apply markdown linting rules
- Highlight code related text
- Enforce line break
- Move links to the bottom of each document

Signed-off-by: Paul Wallrabe <54737071+raballew@users.noreply.github.com>

### CODE REVIEW

**Comment by engelmi** [comment]
There is already a PR linting the markdown files https://github.com/containers/hirte/pull/114 (although I think its now a bit outdated). As stated there (https://github.com/containers/hirte/pull/114#pullrequestreview-1286655881), I also favor the in-place links over the links at the bottom.

**Review by mwperina — CHANGES_REQUESTED** [review]
I'd really like to know:

1. Why we should use 80 chars per line today? 120 chars per line is much more common today
2. Why we should use indirect links (using `[N]` inplace and then in the end of document has list of `[N]` pointing to direct links

**Comment by raballew** [comment]
@engelmi My bad. I did not know that there is already a PR for this. Should I continue working on this one?

@mwperina 

1) There was limit on chars per line in the documents so far (or at least not consistently applied). I guess the amount of chars is a question of preference. On my monitor at least (with the font size I use) 80 chars fit perfectly into half the screen. 120 chars do not.

2) I think everyone will answer this differently. For me the primary reason behind using indirect links is to improve the readability by removing lengthy URLs from the text blocks and replacing them with references.

**Comment by mwperina** [comment]
Take a look at https://github.com/containers/hirte/pull/136 and if you think this PR is still needed please rebase and update

**Comment by engelmi** [comment]
The markdown improvements (as well as adding tooling to automate it) have been done in #136. So I would close this PR.

**Pull request closed without merging**
