### PR TITLE
Hirtectl - Fix endless loop in status call

### PR DESCRIPTION
**Pull request by ygalblum**
Change types to size_t
Keep all variables values positive

### CODE REVIEW

**Review by engelmi — APPROVED** [review]
LGTM

Could we test this by replacing [this line in the integration tests](https://github.com/containers/hirte/blob/main/tests/tests/tier0/hirte-agent-started-and-connected/test_agent_started_and_connected.py#L17) with the usage of `hirtectl`? Just querying and getting a response should be enough.

**Comment by dougsland** [comment]
lgtm

**Comment by rhatdan** [comment]
LGTM

**Comment by ygalblum** [comment]
If we plan to release a 0.4.x, this should be part of it

**Pull request merged**
