### PR TITLE
Add GetSystemResources D-Bus API

### PR DESCRIPTION
**Pull request by dofmind**
Adding GetSystemResources D-Bus API and integration test for getting the system resources of the node.

Related https://github.com/containers/bluechi/issues/589

### CODE REVIEW

**Comment by dofmind** [comment]
I updated commits to fix lint errors.

**Comment by alexlarsson** [comment]
I'm not sure this is the right direction of the project. Bluechi is essentially a frontend for existing systemd apis. Once we start implementing our own functionallity that implies much deeper requirements in terms of API design and implementation, both currently and as things change over time.

**Comment by engelmi** [comment]
> I'm not sure this is the right direction of the project. Bluechi is essentially a frontend for existing systemd apis. Once we start implementing our own functionallity that implies much deeper requirements in terms of API design and implementation, both currently and as things change over time.

I agree and responded on the linked issue https://github.com/containers/bluechi/issues/589 accordingly (also providing a basic suggestion on how to implement this feature without BlueChi). I am afraid this feature is out of scope for BlueChi and we have to reject this PR.

**Comment by dofmind** [comment]
If the scope for BlueChi is limited to APIs of systemd, i agree to reviewer's comments too. As engelmi suggests, then we should try to provide the feature without BlueChi. I will close this PR. Thanks for the guide.

**Pull request closed without merging**
