### PR TITLE
Rename `bluechi` to `bluechi-controller`

### LINKED ISSUE #569: Rename `bluechi` service name to `bluechi-controller`
To distinguish between the project name and controller service name we should rename `bluechi` service name to `bluechi-controller`.  And to align the service name with configuration files we should also rename them:

* `/etc/bluechi/bluechi.conf` -> `/etc/bluechi/controller.conf`
* `/etc/bluechi/bluechi.conf.d` -> `/etc/bluechi/controller.conf.d`
* `/usr/share/bluechi/config/bluechi.conf` -> `/usr/share/bluechi/config/controller.conf`

And also `[bluechi]` section in configuration files should be renamed to `[bluechi-controller]`.

### PR DESCRIPTION
**Pull request by mwperina**
Renames `bluechi` systemd service name to `bluechi-controller`. To aling
with this change also configuration file names for `bluechi-controller`
has been renamed:

* `/etc/bluechi/bluechi.conf` -> `/etc/bluechi/controller.conf`
* `/etc/bluechi/bluechi.conf.d` -> `/etc/bluechi/controller.conf.d`
* `/usr/share/bluechi/config/bluechi.conf` -> `/usr/share/bluechi/config/controller.conf`

Fixes: https://github.com/containers/bluechi/issues/569
Signed-off-by: Martin Perina <mperina@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Are you going to move the daemons to /usr/libexec?

**Comment by dougsland** [comment]
LGTM, pending on @rhatdan question too.

**Comment by dougsland** [comment]
controller naming is a great choice.

**Comment by mwperina** [comment]
> LGTM Are you going to move the daemons to /usr/libexec?

Yes, I will do it in a separate patch

**Review by mkemel — APPROVED** [review]
LGTM

**Pull request merged**
