### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by engelmi**
Hirte release 0.3.0

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by mwperina — APPROVED** [review]
+1

**Comment by dougsland** [comment]
The error not seems related to the change:
```
12:51:09             err:  Problem: conflicting requests
12:51:09             err:   - nothing provides selinux-policy >= 38.1.14-1.el9 needed by hirte-selinux-0.3.0-1.el9.x86_64 from hirte-rpms
12:51:09             out: (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
12:51:09             err: Error: error building at STEP "RUN dnf install -y --repo hirte-rpms     --repofrompath hirte-rpms,file:///tmp/hirte-rpms/     --nogpgcheck hirte hirte-debuginfo hirte-agent hirte-agent-debuginfo hirte-ctl hirte-ctl-debuginfo hirte-selinux": error while running runtime: exit status 1
```

**Comment by mwperina** [comment]
I'd try to rebuild the tests container, then selinux version should match again

**Comment by dougsland** [comment]
@engelmi @rhatdan @mwperina  Should we wait this one for the release:
https://github.com/containers/hirte/pull/322 ?  It seems very close to the merge.

**Comment by engelmi** [comment]
> I'd try to rebuild the tests container, then selinux version should match again

@mwperina Yes, pushed the fixed image already manually and created the PR with the changes #327 


> @engelmi @rhatdan @mwperina Should we wait this one for the release: #322 ? It seems very close to the merge.

@dougsland Yes, I wanted to wait for that PR to be merged (its actually ready to be merged), but the issue with the integration tests caused a delay.

**Review by dougsland — APPROVED** [review]

**Pull request merged**
