### PR TITLE
Add markdown linter to the project

### PR DESCRIPTION
**Pull request by mwperina**
- Add markdownlint-cli2 linter to the project
- Fix markdown syntax issues in doc/arch/README.md
- Fix markdown syntax issues in GH issue templates
- Fix markdown syntax issues in dbus-interfaces.md
- Fix markdown syntax issues in README*md

### CODE REVIEW

**Review by alexlarsson — APPROVED** [review]
lgtm

**Review by engelmi — COMMENTED** [review]
I haven't used a markdown linter yet. Which tool can I use to fix those errors or is it manual work? If there is a tool, can add it as a make target and/or mention it in the dev README.

**Comment by mwperina** [comment]
> I haven't used a markdown linter yet. Which tool can I use to fix those errors or is it manual work? If there is a tool, can add it as a make target and/or mention it in the dev README.

Done

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
