### PR TITLE
Multi host support

### PR DESCRIPTION
**Pull request by engelmi**
Related to: https://github.com/eclipse-bluechi/bluechi/issues/662

In order to allow the integration tests being run on multiple hosts, it is necessary to connect to them via SSH. This has been enabled by moving the functions to create and get files as well as execute commands to a client class which abstracts the communication to either a container or a remote machine via SSH.
Since the host can either be a container or a remote machine, the container class has been renamed to machine and implemented for the controller and agent. The client used there can be set dynamically.
Functions encapsulating systemctl or bluechictl commands were moved to dedicated classes so that is clear which functionality is being used.
The test class has also been changed so that either a container or SSH setup is being used as this affects the setup as well as the teardown. For example, a containerized setup can simply remove the container while any added or changed files on a remote machine need to be cleaned up properly.

## How to test locally

The second commits adds an example on how to use the new functionality. It can easily be tested via container and accesst them via SSH. For example using the script from the terraform-provider:
https://github.com/eclipse-bluechi/terraform-provider-bluechi/blob/main/container/container-setup.sh
```bash
# in cloned tf provider repo
cd terraform-provider-bluechi
bash ./container/container-setup.sh build_image centos
bash ./container/container-setup.sh start centos
```
It spins up multiple containers which can be connected to via SSH (make sure the proper key is used). 

Then change the `tests/plans/multihost.fmf` to use the proper path to the ssh key or password and run it via
```bash
cd tests/
tmt run plans --name multihost -v
```

**Note:** 
- For the initial containerized version, nothing changes. 
- The commit adding the example will be removed before merge.

**Current limitations of the new SSH version:**
Not yet implemented proper cleanup (e.g. uninstall of rpm, restoring changed files)

### CODE REVIEW

**Review by dougsland — COMMENTED** [review]
LGTM

**Comment by dougsland** [comment]
this is huge patch but seems good to my eyes!

**Comment by dougsland** [comment]
@Yarboa 👀

**Comment by engelmi** [comment]
Since this PR is quite huge and does multiple changes, we'll split it up into multiple PRs:
- [x] renaming `controller` to `machine` in classes and functions
- [x] introducing a `Client` class as a base for a container and ssh one (ssh can be a dummy)
- [x] extracting and encapsulating common `exec_run(...)` into dedicated systemctl and bluechictl classes (easier readability and quicker to see which tool is used)
- [x] implementing ssh client and multihost support

Updated #662 as well.

**Pull request closed without merging**
