### PR TITLE
Simplify the test metadata to prevent duplication

### PR DESCRIPTION
**Pull request by psss**
The stuff which is common across tests can be easily shared thanks to `fmf` inheritance [1]. This prevents unnecessary duplication and makes it easier to do changes at one place in the future.

[1] https://fmf.readthedocs.io/en/latest/features.html#inheritance

### CODE REVIEW

**Review by engelmi — APPROVED** [review]
LGTM

**Comment by mwperina** [comment]
Haven't we accidentally also removed also tier selection? We are not using now, but it will probably be used in future ...

**Comment by psss** [comment]
The `tier` key is also set for all tests under the `tier0` directory:

https://github.com/containers/hirte/blob/9c586835ebe786152ebbdedeb9f9c2465463e66c/tests/tests/tier0/main.fmf#L1

In this way it is prepared for future extensions.

**Comment by mwperina** [comment]
> The `tier` key is also set for all tests under the `tier0` directory:
> 
> https://github.com/containers/hirte/blob/9c586835ebe786152ebbdedeb9f9c2465463e66c/tests/tests/tier0/main.fmf#L1
> 
> In this way it is prepared for future extensions.

Ahh, I missed that. Thanks for explanation!

**Pull request merged**
