### PR TITLE
Optimize code coverage processing

### PR DESCRIPTION
**Pull request by mwperina**
- Log test execution and code coverage collection times
- Align pytest execution for code coverage with integration tests
- Generate coverage info files within containers

### CODE REVIEW

**Comment by mwperina** [comment]
@ArtiomDivak

**Comment by mwperina** [comment]
On my machine test execution with code coverage enabled takes around 460 seconds, this patch decreases the execution time approximately to 170 seconds.

**Review by engelmi — APPROVED** [review]
LGTM

**Review by ArtiomDivak — APPROVED** [review]
LGTM

**Pull request merged**
