### PR TITLE
added tmt serial no. to container name

### PR DESCRIPTION
**Pull request by engelmi**
Added TMT serial number to container names in order to prevent cascading failures when containers from previous tests aren't properly cleaned up.

### CODE REVIEW

**Review by ArtiomDivak — APPROVED** [review]
LGTM

**Review by mwperina — COMMENTED** [review]
Shouldn't we always aim to properly clean up things after a test failure?

**Comment by dougsland** [comment]
LGTM, please see Martin's comment.

**Comment by engelmi** [comment]
> Shouldn't we always aim to properly clean up things after a test failure?

Ideally, after each test the teardown would cleanup all containers properly, yes. However, in some cases it'll still happen that containers remain, e.g. when the container is (not yet) in a running state and doesn't react on commands via API. Using the serial number in the container names also enables us to run all tests in parallel in the future (if we want to).

**Comment by mwperina** [comment]
> > Shouldn't we always aim to properly clean up things after a test failure?
> 
> Ideally, after each test the teardown would cleanup all containers properly, yes. However, in some cases it'll still happen that containers remain, e.g. when the container is (not yet) in a running state and doesn't react on commands via API. Using the serial number in the container names also enables us to run all tests in parallel in the future (if we want to).

OK, then. But for multihost support we will need to add reasonable clean up support for each test, because we will not reinstall all changes performed by each test, we will continue with the same host. So proper clean up is important

**Review by mwperina — APPROVED** [review]
LGTM

**Pull request merged**
