### PR TITLE
Replace bluechi-controller by bluechi-agent in docs

### PR DESCRIPTION
**Pull request by cverna**
This commit fixes the single node getting started documentation with the bluechi-agent header in the agent.conf.d file

### CODE REVIEW

**Comment by engelmi** [comment]
Hi @cverna ,
Thanks a lot for your contribution!
Bluechi is part of Eclipse Foundation, so we need to follow the contribution guidelines and as such contributors need to sign the Eclipse Contribution Agreement: https://www.eclipse.org/legal/ECA.php
Could you please create an Eclipse account and sign ECA there?

**Comment by cverna** [comment]
I just signed the ECA

**Comment by engelmi** [comment]
> I just signed the ECA

Thanks!

**Review by engelmi — APPROVED** [review]
LGTM

**Pull request merged**
