### PR TITLE
Publish code coverage reports on the web

### PR DESCRIPTION
**Pull request by mwperina**
Code coverage reports can be generated during integration test run, but
at the moment we have following limitations:

1. We are not running integration tests with code coverage report
   enabled after a PR is merged
2. At this moment there is no way to create GH job which would wait
   until integration tests executed using packit are finished and fetch
   the code coverage results
3. We don't have allowed to merge content to bluechi repo automatically
   as a result of some CI workflow
4. Code coverage report is generated using lcov as an HTML (lcov doesn't
   provide the option to generate report in markdown) and readthedocs.io
   doesn't provide a way to import existing HTML files

So this patch describes a manual flow to publish code coverage report
results into our documentation web site bluechi.readthedocs.io

Signed-off-by: Martin Perina <mperina@redhat.com>

### CODE REVIEW

**Comment by mwperina** [comment]
Here is the screenshot of code coverage report on our web site
Screenshot from 2024-01-05 18-35-28

**Comment by mwperina** [comment]
@ArtiomDivak

**Review by ArtiomDivak — APPROVED** [review]
LGTM

**Review by engelmi — COMMENTED** [review]
I am not sure this is the right approach. It involves a lot of manual work - running the tests to get the coverage artifacts needs to be done locally on a developers machine and then it needs to be updated by committing to the repo. 

I tried to create a proposal that runs the integration tests with coverage in the GH workflow, extracting the coverage HTML report and adding a comment with the summary to the PR here: 
https://github.com/eclipse-bluechi/bluechi/pull/690
It would look like in this example here: https://github.com/nwutils/nw-electron-adapter/pull/5#issuecomment-734581491

Current problem is that the `GITHUB_TOKEN` apparently doesn't have the proper permissions in the eclipse orga. Will have to look into that and created a PR to the self-service repo (https://github.com/eclipse-bluechi/.eclipsefdn/pull/11).

**Comment by mwperina** [comment]
Closing in favor of https://github.com/eclipse-bluechi/bluechi/issues/694

**Pull request closed without merging**
