### PR TITLE
rust: Add BlueChi Rust module

### PR DESCRIPTION
**Pull request by dougsland**
Initial commit to include the BlueChi Rust module and a list_nodes example.

Welcome Rust to BlueChi family! \o/

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

### CODE REVIEW

**Comment by dougsland** [comment]
```
# dnf install rust cargo
# pwd
$HOME/bluechi/src/bindings/rust

# cargo run
    Updating crates.io index
   Compiling pkg-config v0.3.27
   Compiling libc v0.2.147
   Compiling libdbus-sys v0.2.5
   Compiling dbus v0.9.7
   Compiling bluechi v0.1.0 (/root/rust/src/bluechi/src/bindings/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 7.48s
     Running `target/debug/bluechi`
Node: "control"
Status: "online"
Path("/org/eclipse/bluechi/node/control\0")
Node: "node1"
Status: "offline"
Path("/org/eclipse/bluechi/node/node1\0")
```

**Comment by dougsland** [comment]
@engelmi have i shared that markdown lints are "bad"? ;-)

**Comment by dougsland** [comment]
Later we need to publish our module in crates.io but can be done later.

**Comment by engelmi** [comment]
> @engelmi have i shared that markdown lints are "bad"? ;-)

Yes, its a pain sometimes :wink:

**Review by engelmi — CHANGES_REQUESTED** [review]
I don't think a Rust cargo where we only provide the generated code from `dbus-codegen` makes much sense. Since Rust, Go and other compiled languages have a build step, this code can and should simply be generated in the respective projects based on the .xml files. For the python bindings we added the typing on top, which is simplifies development. But for Rust or so we don't add anything. 
I think it would be good to provide a few Rust examples similar to GoLang instead. (https://github.com/containers/bluechi/tree/main/doc/api-examples/go)

**Comment by dougsland** [comment]
> I don't think a Rust cargo where we only provide the generated code from `dbus-codegen` makes much sense.
> Since Rust, Go and other compiled languages have a build step, this code can and should simply be generated
> in the respective projects based on the .xml files. For the python bindings we added the typing on top, which is
> simplifies development. But for Rust or so we don't add anything. I think it would be good to provide a few Rust
> examples similar to GoLang instead. (https://github.com/containers/bluechi/tree/main/doc/api-examples/go)

Hey @engelmi 

I thought could be a good idea to provide such module to users as it saves a ton of time when developing in Rust + BlueChi (as I shared in the main.rs). For me that's fine to provide a simple example of Rust + D-bus library too and based on that users can create their own libraries.

**Comment by dougsland** [comment]
solved by: https://github.com/containers/bluechi/pull/537

**Pull request closed without merging**
