### PR TITLE
Optimize bluechictl-is-enabled test

### PR DESCRIPTION
**Pull request by mwperina**
To improve performance of bluechictl-is-enabled test we will skip
checking existing unit file, if we already checked a unit with the same
enablement status before, when we traverse over list of all existing
unit files.

Relates: https://github.com/eclipse-bluechi/bluechi/issues/972
Signed-off-by: Martin Perina <mperina@redhat.com>

### CODE REVIEW

**Review by mkemel — APPROVED** [review]
LGTM

**Review by engelmi — COMMENTED** [review]
In general LGTM

By using the `list-unit-files` feature, we rely on the state of the machine (container/vm/etc.) - so it might behave differently in our container vs multi-host setup. In addition, the `list-unit-files` is quite expensive and takes quite a while to complete. 
Therefore I'd like to raise the question if it is really necessary to aim for checking all systemd unit file states or to "just" select a few and enforce these - e.g. create a quadlet file, do a reload and check if the file is "generated".

**Comment by mwperina** [comment]
> In general LGTM
> 
> By using the `list-unit-files` feature, we rely on the state of the machine (container/vm/etc.) - so it might behave differently in our container vs multi-host setup. In addition, the `list-unit-files` is quite expensive and takes quite a while to complete. Therefore I'd like to raise the question if it is really necessary to aim for checking all systemd unit file states or to "just" select a few and enforce these - e.g. create a quadlet file, do a reload and check if the file is "generated".

I used units from list-unit-files, because I haven't been able to find out a way to create services with all possible enablement statuses to make sure we simulate systemctl behavior as much as possible. So using list-unit-files we are currently checking services with following enablement statuses (at least on my laptop):

- static
- alias
- disabled
- enabled
- indirect
- enabled-runtime

And the manually we check for non-existent unit file.

So for now I'd merge the code to unblock slower platforms and later we can investigate better solution as a part of https://github.com/eclipse-bluechi/bluechi/issues/976

**Comment by engelmi** [comment]
> I used units from list-unit-files, because I haven't been able to find out a way to create services with all possible enablement statuses to make sure we simulate systemctl behavior as much as possible. So using list-unit-files we are currently checking services with following enablement statuses (at least on my laptop):
> 
>     * static
>     * alias
>     * disabled
>     * enabled
>     * indirect
>     * enabled-runtime
> 
> And the manually we check for non-existent unit file.

That was my previous point - it relies on the machine we run it on. In this list the states `generated` and `transient` are missing, for example. So it is not exhaustive. Because of this I am wondering if we are optimizing the wrong thing and if a more static approach with just a few state checks should be chosen - which doesn't need investigation, we'd just need to decide.

> So for now I'd merge the code to unblock slower platforms and later we can investigate better solution as a part of #976

Sounds reasonable to me. Both, merging now or changing the approach, is fine.

**Pull request merged**
