### PR TITLE
Fixed duplicate tmt test ids

### PR DESCRIPTION
**Pull request by engelmi**
Fixed duplicate tmt test ids in integration tests.

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by dracher** [comment]
LGTM, and it's suprised tmt doesn't check id duplicated possibility

**Comment by engelmi** [comment]
> LGTM, and it's suprised tmt doesn't check id duplicated possibility

I agree. Created an RFE issue for this: https://github.com/teemtee/tmt/issues/2939

**Pull request merged**
