### PR TITLE
hirte config files should be called the same everywhere

### PR DESCRIPTION
**Pull request by rhatdan**
hirte-agent should read the agent.conf file in /usr and optionally in /etc.

Not sure why we are installing this file twice, but definitely do not want it named differently.  Distros should install in /usr/share/hirte/config/ and admins can copy it to /etc/hirte/

Similarly hirte should read hirte.conf should be in both locations.

### CODE REVIEW

**Comment by mwperina** [comment]
https://github.com/containers/hirte/issues/147 describes existing configuration files location and purpose

**Comment by rhatdan** [comment]
I personally don't like having files installed by default in /etc, if possible. Now or soon you would not need a config file by default. The directories are fine, but I don't see the reason for the files. One issue with having the files automatically in /etc is when systemd updates them it has issues, either creating backup files or removing them.
Having them with different names to me was very hard to understand.

hirte-default.conf being the default for agent.conf?

I would prefer to have the agent.conf and hirte.conf currently installed in /etc to be installed in /usr/share and then admin can simply copy them to /etc directory. or use the conf.d subdirs.

**Comment by alexlarsson** [comment]
It seems like this just deletes the default files, but i think we need those default set, because the defaults is not otherwise built into hirte. So, rather than we should rename hirte-default.conf to hirte.conf and then install that to usr.

**Comment by alexlarsson** [comment]
Alternatively we should hardcode defaults like the port in the actual code, and then we don't need the default file to have a value for it.

**Comment by alexlarsson** [comment]
I think the later is probably better than falling over if the default file is not found

**Comment by engelmi** [comment]
> Alternatively we should hardcode defaults like the port in the actual code, and then we don't need the default file to have a value for it.

Defaults for the port and, recently, for the [manager host](https://github.com/containers/hirte/pull/247) and the [node name](https://github.com/containers/hirte/pull/245) have been hardcoded already. However, we probably might want to rethink the structure (later).

**Comment by rhatdan** [comment]
@alexlarsson @mwperina @engelmi @pypingou PTAL

I think this is ready to merge.

**Review by engelmi — APPROVED** [review]
LGTM

**Review by mwperina — APPROVED** [review]
+1

**Review by pypingou — APPROVED** [review]

**Pull request merged**
