### PR TITLE
remove warnings from hashmap lib

### LINKED ISSUE #459: build: remove warnings from hashmap lib
## Describe the bug
```
[18/68] Compiling C object subprojects/hashmap.c/libhashmapc.a.p/hashmap.c.o
../subprojects/hashmap.c/hashmap.c: In function ‘hashmap_new_with_allocator’:
../subprojects/hashmap.c/hashmap.c:91:13: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   91 |     if (cap < ncap) {
      |             ^
../subprojects/hashmap.c/hashmap.c:94:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   94 |         while (ncap < cap) {
      |                     ^
../subprojects/hashmap.c/hashmap.c: In function ‘hashmap_murmur’:
../subprojects/hashmap.c/hashmap.c:608:50: warning: unused parameter ‘seed1’ [-Wunused-parameter]
  608 |                         uint64_t seed0, uint64_t seed1)
      |                                         ~~~~~~~~~^~~~~
../subprojects/hashmap.c/hashmap.c: In function ‘SIP64’:
../subprojects/hashmap.c/hashmap.c:507:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  507 |     case 7: b |= ((uint64_t)in[6]) << 48;
      |             ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:508:5: note: here
  508 |     case 6: b |= ((uint64_t)in[5]) << 40;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:508:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  508 |     case 6: b |= ((uint64_t)in[5]) << 40;
      |             ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:509:5: note: here
  509 |     case 5: b |= ((uint64_t)in[4]) << 32;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:509:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  509 |     case 5: b |= ((uint64_t)in[4]) << 32;
      |             ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:510:5: note: here
  510 |     case 4: b |= ((uint64_t)in[3]) << 24;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:510:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  510 |     case 4: b |= ((uint64_t)in[3]) << 24;
      |             ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:511:5: note: here
  511 |     case 3: b |= ((uint64_t)in[2]) << 16;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:511:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  511 |     case 3: b |= ((uint64_t)in[2]) << 16;
      |             ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:512:5: note: here
  512 |     case 2: b |= ((uint64_t)in[1]) << 8;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:512:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  512 |     case 2: b |= ((uint64_t)in[1]) << 8;
      |             ~~^~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:513:5: note: here
  513 |     case 1: b |= ((uint64_t)in[0]); break;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c: In function ‘MM86128’:
../subprojects/hashmap.c/hashmap.c:567:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  567 |     case 15: k4 ^= tail[14] << 16;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:568:5: note: here
  568 |     case 14: k4 ^= tail[13] << 8;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:568:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  568 |     case 14: k4 ^= tail[13] << 8;
      |              ~~~^~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:569:5: note: here
  569 |     case 13: k4 ^= tail[12] << 0;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:570:58: warning: this statement may fall through [-Wimplicit-fallthrough=]
  570 |              k4 *= c4; k4  = ROTL32(k4,18); k4 *= c1; h4 ^= k4;
      |                                                       ~~~^~~~~
../subprojects/hashmap.c/hashmap.c:571:5: note: here
  571 |     case 12: k3 ^= tail[11] << 24;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:571:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  571 |     case 12: k3 ^= tail[11] << 24;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:572:5: note: here
  572 |     case 11: k3 ^= tail[10] << 16;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:572:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  572 |     case 11: k3 ^= tail[10] << 16;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:573:5: note: here
  573 |     case 10: k3 ^= tail[ 9] << 8;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:573:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  573 |     case 10: k3 ^= tail[ 9] << 8;
      |              ~~~^~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:574:5: note: here
  574 |     case  9: k3 ^= tail[ 8] << 0;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:575:58: warning: this statement may fall through [-Wimplicit-fallthrough=]
  575 |              k3 *= c3; k3  = ROTL32(k3,17); k3 *= c4; h3 ^= k3;
      |                                                       ~~~^~~~~
../subprojects/hashmap.c/hashmap.c:576:5: note: here
  576 |     case  8: k2 ^= tail[ 7] << 24;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:576:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  576 |     case  8: k2 ^= tail[ 7] << 24;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:577:5: note: here
  577 |     case  7: k2 ^= tail[ 6] << 16;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:577:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  577 |     case  7: k2 ^= tail[ 6] << 16;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:578:5: note: here
  578 |     case  6: k2 ^= tail[ 5] << 8;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:578:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  578 |     case  6: k2 ^= tail[ 5] << 8;
      |              ~~~^~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:579:5: note: here
  579 |     case  5: k2 ^= tail[ 4] << 0;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:580:58: warning: this statement may fall through [-Wimplicit-fallthrough=]
  580 |              k2 *= c2; k2  = ROTL32(k2,16); k2 *= c3; h2 ^= k2;
      |                                                       ~~~^~~~~
../subprojects/hashmap.c/hashmap.c:581:5: note: here
  581 |     case  4: k1 ^= tail[ 3] << 24;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:581:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  581 |     case  4: k1 ^= tail[ 3] << 24;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:582:5: note: here
  582 |     case  3: k1 ^= tail[ 2] << 16;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:582:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  582 |     case  3: k1 ^= tail[ 2] << 16;
      |              ~~~^~~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:583:5: note: here
  583 |     case  2: k1 ^= tail[ 1] << 8;
      |     ^~~~
../subprojects/hashmap.c/hashmap.c:583:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  583 |     case  2: k1 ^= tail[ 1] << 8;
      |              ~~~^~~~~~~~~~~~~~~~
../subprojects/hashmap.c/hashmap.c:584:5: note: here
  584 |     case  1: k1 ^= tail[ 0] << 0;
```

### PR DESCRIPTION
**Pull request by Iiqbal2000**
Fixes: #459

Remove warning messages from hashmap.c  by casting raw pointers to each original object

### CODE REVIEW

**Comment by Iiqbal2000** [comment]
Please check my PR @engelmi

**Comment by engelmi** [comment]
Thanks again for your contribution! @Iiqbal2000 

The changes look good. I think what is missing is switching from hashmap.c `v0.6.1` to `v0.7.0`. To do this, go to the hashmap.c directory:
```bash
$ cd subprojects/hashmap.c
$ git status
HEAD detached at v0.6.1
```
and checkout the newer version:
```bash
# in subproject/hashmap.c
$ git checkout v0.7.0
Previous HEAD position was 1b0e097 added meson build
HEAD is now at b32c16f added meson build
```
Add this change as well to this PR and build/test should be fine. 

Oh, and please update the PR with the latest changes from main.

**Comment by Iiqbal2000** [comment]
I have updated it, please check it again @engelmi

**Review by engelmi — APPROVED** [review]
LGTM
Nice work!

**Pull request merged**
