### PR TITLE
Measure Job time on agent and return it

### PR DESCRIPTION
**Pull request by mkemel**
The agent measures time for the systemd job to finish, and returns it with the JobDone signal, and then the manager returns it with JobRemoved signal.
Given this, we can time the whole operation, and see hirte overhead in different setups.

### CODE REVIEW

**Comment by alexlarsson** [comment]
Overall the code looks good to me, but I'm not exactly sure what the goal of this particular measure is. The returned time will be dominated by the time it took to actually start the service itself, which will have a high variability. How do you propose we derive hirte-specific overhead data from this number?

**Comment by alexlarsson** [comment]
Also, can't much of this be extracted from the pre-existing unit timestamps, like InactiveExitTimestamp and ActiveEnterTimestamp. 

Really, if we want to know the hirte overhead, should we not rather do the time measurements in the manager, and then subtract these systemd-side timestamp from the result? That would be the "overhead", no?

**Comment by mkemel** [comment]
@alexlarsson 
I thought that this time could be subtracted from the overall time it took for the manager to run the command at the client level, and there we have the overhead. But this would include also the time between the unit really started/stopped and the time the agent received JobRemoved signal. You are right, this is not what we need.

Regarding what you proposed, this would require the manager and agent clocks to be absolutely synched. Can we assume that?

**Comment by mkemel** [comment]
Also I thought about more usable way to provide measurement results - by emitting designated metrics signal. This is a more expandable solution, and it makes it easier for a user to consume metrics data, e.g. if he wants to have a different process to do that, and also this way this can be disabled on the manager side. @alexlarsson WDYT?

**Comment by alexlarsson** [comment]
So, i think what we want is the time from hirte manager recieving the job request to it reporting it done minus the time systemd spent starting it. This later time is, I believe available as  `ActiveEnterTimestamp - InactiveExitTimestamp`, which we already can get as property change events on the monitor.

**Pull request closed without merging**
